/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IPost } from "./store/state-types";
export namespace Components {
    interface AppCard {
        "cardDetails": IPost;
    }
    interface AppEditcard {
    }
    interface AppPagination {
        "paginate": (number: number) => void;
        "postsPerPage": number;
        "totalPosts": number;
    }
    interface AppPosts {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppCardElement extends Components.AppCard, HTMLStencilElement {
    }
    var HTMLAppCardElement: {
        prototype: HTMLAppCardElement;
        new (): HTMLAppCardElement;
    };
    interface HTMLAppEditcardElement extends Components.AppEditcard, HTMLStencilElement {
    }
    var HTMLAppEditcardElement: {
        prototype: HTMLAppEditcardElement;
        new (): HTMLAppEditcardElement;
    };
    interface HTMLAppPaginationElement extends Components.AppPagination, HTMLStencilElement {
    }
    var HTMLAppPaginationElement: {
        prototype: HTMLAppPaginationElement;
        new (): HTMLAppPaginationElement;
    };
    interface HTMLAppPostsElement extends Components.AppPosts, HTMLStencilElement {
    }
    var HTMLAppPostsElement: {
        prototype: HTMLAppPostsElement;
        new (): HTMLAppPostsElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-card": HTMLAppCardElement;
        "app-editcard": HTMLAppEditcardElement;
        "app-pagination": HTMLAppPaginationElement;
        "app-posts": HTMLAppPostsElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppCard {
        "cardDetails"?: IPost;
    }
    interface AppEditcard {
    }
    interface AppPagination {
        "paginate"?: (number: number) => void;
        "postsPerPage"?: number;
        "totalPosts"?: number;
    }
    interface AppPosts {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-card": AppCard;
        "app-editcard": AppEditcard;
        "app-pagination": AppPagination;
        "app-posts": AppPosts;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-card": LocalJSX.AppCard & JSXBase.HTMLAttributes<HTMLAppCardElement>;
            "app-editcard": LocalJSX.AppEditcard & JSXBase.HTMLAttributes<HTMLAppEditcardElement>;
            "app-pagination": LocalJSX.AppPagination & JSXBase.HTMLAttributes<HTMLAppPaginationElement>;
            "app-posts": LocalJSX.AppPosts & JSXBase.HTMLAttributes<HTMLAppPostsElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
